"""Public contracts shared by GUI implementations and controllers.

The contracts deliberately contain no Tkinter, Qt, model, or API imports.  A
future PySide6 view can implement the same surface without depending on the
current Tkinter implementation.
"""

from dataclasses import dataclass
from typing import Any, Callable, Protocol, TypedDict


Callback = Callable[[], None]


class MonitorForm(TypedDict):
    """Raw, toolkit-neutral values currently entered in the monitor screen."""

    api_key: str
    keyword_rules: list[dict[str, Any]]
    interval: str
    result_interval: str
    windows_notifications_enabled: bool
    notify_all_opening_results: bool
    keyword_email_enabled: bool
    attachment_download_dir: str


@dataclass(frozen=True)
class MainViewState:
    """Values needed to construct the main screen, detached from AppConfig."""

    api_key: str
    interval: str
    result_interval: str
    keyword_rules: tuple[dict[str, Any], ...]
    windows_notifications_enabled: bool
    notify_all_opening_results: bool
    keyword_email_enabled: bool
    attachment_download_dir: str


@dataclass(frozen=True)
class EmailSettingsState:
    """Values displayed by the email settings window."""

    smtp_host: str
    smtp_port: int
    smtp_username: str
    smtp_sender_name: str


class CommonViewProtocol(Protocol):
    def post(self, callback: Callback) -> None: ...

    def schedule(self, delay_ms: int, callback: Callback) -> None: ...

    def set_close_handler(self, callback: Callback) -> None: ...

    def stop_dispatcher(self) -> None: ...

    def destroy(self) -> None: ...

    def log(self, message: str) -> None: ...

    def set_status(self, message: str) -> None: ...

    def show_info(self, title: str, message: str, parent: Any = None) -> None: ...

    def show_warning(self, title: str, message: str, parent: Any = None) -> None: ...

    def show_error(self, title: str, message: str, parent: Any = None) -> None: ...

    def ask_yes_no(self, title: str, message: str, parent: Any = None) -> bool: ...

    def update_running_ui(self, is_running: bool) -> None: ...


class BidMonitorViewProtocol(Protocol):
    def get_monitor_form(self) -> MonitorForm: ...

    def set_all_keyword_monitoring(self, enabled: bool) -> None: ...

    def set_keyword_monitoring(self, rule_id: str, enabled: bool) -> None: ...

    def set_attachment_download_directory(self, directory: str) -> None: ...

    def set_check_summary(
        self, checked_at: Any, new_alert_count: int, all_success: bool, interval: int
    ) -> None: ...

    def set_monitor_summary(self, summary: str) -> None: ...

    def set_next_check_pending(self) -> None: ...

    def clear_next_check(self) -> None: ...

    def start_manual_check(self) -> None: ...

    def finish_manual_check(self) -> None: ...


class SavedBidsViewProtocol(Protocol):
    def get_lookup_reference(self) -> str: ...

    def get_lookup_type(self) -> str: ...

    def set_lookup_reference(self, value: str) -> None: ...

    def get_lookup_notice(self) -> Any: ...

    def begin_lookup_notice(self) -> None: ...

    def finish_lookup_notice(self, notice: Any, error: Any, duplicate: Any = None) -> None: ...

    def get_saved_search_text(self) -> str: ...

    def get_saved_filters(self) -> dict[str, str]: ...

    def get_saved_sort(self) -> tuple[str, bool]: ...

    def render_saved_bids(self, rows: Any) -> None: ...

    def select_saved_bid(self, saved_id: int) -> None: ...

    def get_selected_saved_bid(self) -> Any: ...

    def get_result_interval_text(self) -> str: ...

    def set_saved_monitor_status(self, text: str) -> None: ...

    def set_saved_result_status(self, text: str) -> None: ...

    def render_saved_result_auto_check(self, summary: dict[str, Any]) -> None: ...

    def render_saved_result_check(self, summary: Any, error: Any) -> None: ...

    def show_saved_bid_detail(self, detail: dict[str, Any]) -> Any: ...

    def show_notice_version_history(self, row: Any, versions: Any, comparison: Any) -> None: ...


class RecentAlertViewProtocol(Protocol):
    def add_recent_alert(self, item_id: str, bid: Any, keywords: list[str]) -> None: ...

    def remove_recent_alert_rows(self, item_ids: Any) -> None: ...

    def clear_recent_alert_rows(self) -> None: ...

    def get_selected_alert_id(self) -> str | None: ...

    def select_first_alert(self) -> None: ...

    def set_unread_alert_count(self, count: int) -> None: ...

    def show_keyword_popup(self, bid: Any, keywords: list[str]) -> None: ...

    def close_keyword_popup(self) -> None: ...


class EmailViewProtocol(Protocol):
    def open_email_settings_window(self, **kwargs: Any) -> Any: ...

    def open_saved_bid_recipient_window(self, **kwargs: Any) -> Any: ...

    def open_keyword_rule_recipient_window(self, **kwargs: Any) -> Any: ...


class AppViewProtocol(
    CommonViewProtocol,
    BidMonitorViewProtocol,
    SavedBidsViewProtocol,
    RecentAlertViewProtocol,
    EmailViewProtocol,
    Protocol,
):
    """Complete surface a GUI toolkit implementation provides."""


class ViewActionsProtocol(Protocol):
    """Actions a view may invoke in response to user input."""

    def start(self, enable_all: bool = True, warn_api_volume: bool = True) -> bool: ...

    def stop(self, disable_all: bool = True) -> None: ...

    def check_now(self) -> None: ...

    def test_alert(self) -> None: ...

    def reset_records(self) -> None: ...

    def acknowledge_alerts(self) -> None: ...

    def keyword_rules_changed(self) -> None: ...

    def set_keyword_rule_monitoring(
        self, rule: dict[str, Any], enabled: bool, on_finished: Callback
    ) -> None: ...

    def save_attachment_download_directory(self, directory: str) -> None: ...

    def reset_attachment_download_directory(self) -> None: ...

    def toggle_windows_notifications(self) -> None: ...

    def toggle_keyword_email_notifications(self) -> None: ...

    def open_email_settings(self) -> None: ...

    def lookup_notice_by_no(self) -> None: ...

    def save_lookup_notice(self) -> None: ...

    def refresh_saved_bids(self, select_id: int | None = None) -> None: ...

    def show_saved_bid_detail(self) -> None: ...

    def show_notice_version_history(self) -> None: ...

    def open_saved_bid_link(self) -> None: ...

    def open_saved_bid_recipients(self) -> None: ...

    def open_keyword_rule_recipients(self, rule_id: str) -> None: ...

    def check_saved_results_now(self) -> None: ...

    def toggle_saved_bid_monitoring(self) -> None: ...

    def permanently_delete_saved_bid(self) -> None: ...

    def apply_saved_result_interval(self) -> None: ...

    def save_result_notification_setting(self) -> None: ...

    def open_selected_alert_link(self) -> None: ...

    def save_selected_alert_bid(self) -> None: ...

    def clear_recent_alerts(self) -> None: ...

    def show_alert_keywords(self, item_id: str) -> None: ...

    def open_log_file(self) -> None: ...

    def open_link(self, link: str) -> None: ...


class ViewFactoryProtocol(Protocol):
    """Factory used by the composition root to select a GUI toolkit."""

    def __call__(
        self,
        root: Any,
        actions: ViewActionsProtocol,
        initial_state: MainViewState,
    ) -> AppViewProtocol: ...
